# Generated by Django 5.1.15 on 2026-06-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Docente'), ('technician', 'Técnico')], default='student', max_length=20),
        ),
    ]
